DROP DATABASE IF EXISTS act32_2_AGM;

CREATE DATABASE act32_2_AGM;

USE act32_2_AGM;

CREATE TABLE SOCIOS (
Cod_socio INT(10) AUTO_INCREMENT,
Nombre VARCHAR(20) NOT NULL,
Dirección VARCHAR(30),
Teléfono VARCHAR(15) NOT NULL,
CONSTRAINT Cod_socio_PK PRIMARY KEY (Cod_socio)
);

CREATE TABLE PELICULA (
Referencia VARCHAR(10),
Título VARCHAR(20) NOT NULL,
Género set('drama', 'acción', 'comedia', 'suspense', 'terror'),
Año_Estreno DATE NOT NULL,
Director VARCHAR(20),
Nacionalidad VARCHAR(20) NOT NULL,
CONSTRAINT Referencia_PK PRIMARY KEY (Referencia),
);

CREATE TABLE PRESTAMOS (
Cod_Socio INT(10),
Referencia_Película VARCHAR (10),
Fecha_Préstamo DATETIME NOT NULL,
Importe FLOAT(3,2) NOT NULL DEFAULT '5,00',
CONSTRAINT Cod_socio_FK FOREIGN KEY (Cod_Socio) REFERENCES SOCIOS
ON UPDATE CASCADE
ON DELETE NO ACTION,
CONSTRAINT Referencia_pelicula_FK FOREIGN KEY (Referencia_Película) REFERENCES PELICULA
ON UPDATE CASCADE
ON DELETE NO ACTION
);
